<?php

return [
    [   'user_id' => 0,
        'title' => "Casa Marte",
        'description' => "bed and breakfast ha tutti i comfort di casa lontano da casa, a pochi minuti dal centro storico, ben collegato con i mezzi pubblici ARIA CONDIZIONATA - BAGNO PRIVATO -WIFI",
        'rooms' => "2",
        'beds' => "5",
        'toilets' => "2",
        'square_meters' => "45",
        'address' => "Via Giovanni Bettolo, 4, Roma",
        'latitude' => "41.91135390127905",
        'longitude' => "12.455312507846944",
        'image' => "https://dhqbz5vfue3y3.cloudfront.net/fotobbit/25246/1/25246_medium.jpg?rfh=60644",
        'visible' => true,
        'messages' => null,
    ],
    [   'user_id' => 1,
        'title' => "B&B Roma 130",
        'description' => "Si trova nel quartiere Vaticano Prati di Roma, a 1,1 km dalla stazione della metropolitana Lepanto, a 800 metri dai Musei Vaticani e a 1,3 km da Piazza San Pietro. La struttura dista circa 1,4 km dal Vaticano, 2,6 km da Castel Sant'Angelo e 2,8 km da Piazza del Popolo. La connessione WiFi gratuita è disponibile in tutta la struttura e la stazione della metropolitana Ottaviano dista 500 metri. Questo spazioso appartamento presenta 2 camere da letto, una TV a schermo piatto e una cucina completamente attrezzata con lavastoviglie, forno, lavatrice, microonde e frigorifero. Gli asciugamani e le lenzuola sono inclusi nell'appartamento. La sistemazione è non fumatori. ",
        'rooms' => "1",
        'beds' => "4",
        'toilets' => "1",
        'square_meters' => "35",
        'address' => "Viale delle Milizie, 32, Roma",
        'latitude' => "41.912643",
        'longitude' => "12.462680",
        'image' => "https://www.dirienzopantheonpalace.it/wp-content/uploads/2019/04/SUITE_CAMERA_HOME.jpg",
        'visible' => true,
        'messages' => null,
    ],
    [   'user_id' => 2,
        'title' => "Casa Romana",
        'description' => " L’atmosfera è accogliente, design dell'appartamento ristrutturato e moderno pieno di luce e contrasti, le camere caratterizzate dai nomi dei monumenti più importanti di Roma che fanno immergere completamente gli ospiti nella stupefacente storia e bellezza della capitale d’Italia.",
        'rooms' => "2",
        'beds' => "5",
        'toilets' => "1",
        'square_meters' => "57",
        'address' => "Via Vittorio Arminjon, 8-14, Roma",
        'latitude' => "41.911218",
        'longitude' => "12.455657",
        'image' => "https://www.bbitalia.it/IMAGES/foto/small/23237-2015-11-19-19-05-23-024.jpg",
        'visible' => true,
        'messages' => null,
    ],
    [   'user_id' => 3,
        'title' => "Casa Mauro",
        'description' => "Situata a Roma, a 1,1 km dai Musei Vaticani e a 1,7 km da Castel Sant'Angelo, la LorVand offre la vista sulla città. La struttura si trova a 600 metri dalla stazione della metropolitana Ottaviano e dispone di ascensore. La stazione della metropolitana Lepanto e il centro città distano rispettivamente 400 metri e 2,1 km. Tutte le camere sono climatizzate e presentano una TV a schermo piatto con servizi di streaming, un minibar, un bollitore, una scrivania, una doccia e un asciugacapelli. Le unità comprendono la connessione WiFi gratuita, un bagno privato con set di cortesia e, in alcuni casi, una terrazza. Lenzuola e asciugamani sono inclusi.",
        'rooms' => "3",
        'beds' => "6",
        'toilets' => "1",
        'square_meters' => "70",
        'address' => "Via Vespasiano, 81, Roma",
        'latitude' => "41.908702",
        'longitude' => "12.456898",
        'image' => "https://www.colosseumsuite.com/wp-content/uploads/appartamento-6-persone-21.jpg",
        'visible' => true,
        'messages' => null,
    ],
    [   'user_id' => 4,
        'title' => "B&B 1250",
        'description' => "Situato a Roma, a 450 mt dai Musei Vaticani, offre la connessione WiFi gratuita e il servizio concierge. La struttura dista 800 m da Piazza San Pietro. Il banco escursioni sarà lieto di fornirvi informazioni sulla zona. Le camere sono dotate di TV a schermo piatto. Tutte le camere dell'Alea Home Roma sono dotate di aria condizionata, armadio.",
        'rooms' => "2",
        'beds' => "6",
        'toilets' => "1",
        'square_meters' => "43",
        'address' => "Borgo Angelico, 12, Roma",
        'latitude' => "1.905158",
        'longitude' => "12.459451",
        'image' => "https://cdn.hometogo.net/medium/v1/14f/1f4/bddffd11c0a0f0e5b11857e9f9.jpg",
        'visible' => true,
        'messages' => null,
    ],
    [   'user_id' => 5,
        'title' => "GrandTourTraveller",
        'description' => "Situato in una buona posizione a Roma, offre una colazione all'italiana e la connessione WiFi gratuita. La struttura si affaccia sulla città e sul giardino e dista 600 metri dalla stazione della metropolitana Lepanto. Potrete anche usufruire di un servizio di trasferimento aeroportuale e di autonoleggio. Le unità abitative sono dotate di aria condizionata, TV a schermo piatto con canali satellitari, frigorifero, bollitore, bidet, asciugacapelli e scrivania. Dispongono inoltre di un bagno privato con doccia e set di cortesia, e, in alcuni casi, di una cucina completamente attrezzata con forno. A disposizione anche biancheria da letto e asciugamani",
        'rooms' => "3",
        'beds' => "6",
        'toilets' => "2",
        'square_meters' => "64",
        'address' => "Via Crescenzio, 58, Roma",
        'latitude' => "41.905796",
        'longitude' => "12.463146",
        'image' => "https://www.bbitalia.it/IMAGES/foto/small/26721-2019-06-25-15-27-09-000.jpg",
        'visible' => true,
        'messages' => null,
    ],
    [    
        'user_id' => 6,
        'title' => "Il tempio di Morfeo",
        'description' => "Situata in un'ottima posizione a Roma e ristrutturata di recente, offre la connessione WiFi gratuita e un parcheggio privato. Questa struttura con ascensore si trova a 400 metri dalla stazione della metropolitana Ottaviano. Le sistemazioni della guest house sono adatte a ospitare le famiglie. Le sistemazioni sono climatizzate e provviste di armadio, macchina da caffè, frigorifero, cassaforte, TV a schermo piatto e bagno privato con doccia. Gli alloggi presentano anche un bollitore e, in alcuni casi, un patio e/o la vista sulla città. Lenzuola e asciugamani sono inclusi.",
        'rooms' => "3",
        'beds' => "5",
        'toilets' => "2",
        'square_meters' => "75",
        'address' => "Via Candia, 6, Roma",
        'latitude' => "41.908547",
        'longitude' => "12.454704",
        'image' => "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/101176744.jpg?k=f60d5d6c8623bfe5f3d944ca43de02766246db96231b5eb9dfab879ebad478c4&o=",
        'visible' => true,
        'messages' => null,
],
];